### ISSUE TITLE
Background and Color Multiplier should use consistent color units

### ISSUE THREAD

**Issue by vchelaru** [KallDrexx/ParME#19]
1. Create an emitter
1. Click **Color Multiplier**
1. Observe color values are normalized (0-1)
1. Click background color
1. Observe color values re 0-255

Expected: Both should use 0-1 or 0-255 consistently. 
Note: Vic suggests 0-255.

![image](https://user-images.githubusercontent.com/729631/94382078-9bc1f080-00f8-11eb-9bb2-f77814c81213.png)

**Comment by KallDrexx** [comment]
Color values are now standardized where RGB values are always 0-255, while alpha is 0.0 - 1.0.  

![dotnet_8zd3dSXtjB](https://user-images.githubusercontent.com/139393/94880713-ba462580-0431-11eb-8609-356af0827528.png)

The color change modifier has been removed, as it was confusing to determine how the color multiplier should change per second.  Instead this was replaced with an `Ending Color Modifier` which allows you to put in what color multiplier you want the particle to have on the last frame of it's lifetime, and the particle will linearly interpolate between its starting and ending color.
