### ISSUE TITLE
Parme should allow rotation to be based on velocity

### ISSUE THREAD

**Issue by profexorgeek** [KallDrexx/ParME#38]
If you fire an arrow into the air in a random upward direction, as the arrow lost velocity and began to travel back towards the ground it would rotate so that the arrowhead always faced its direction of travel. As far as I can tell, Parme doesn't support this behavior. The math is just:
`rotation = Math.Atan2(velocity.Y, velocity.X);`

If this is an option for particle rotation, it should probably override all other things that affect rotation.

**Comment by KallDrexx** [comment]
Added in bf3278323edd5ae4ec2032b18580a99c002ae990 and released in 0.7.6
