### ISSUE TITLE
Parme should allow instantiation of emitters by string

### ISSUE THREAD

**Issue by profexorgeek** [KallDrexx/ParME#46]
This is allowed:
`var emitter = ParmeManager.Instance.CreateEmitter(new MyEmitterType(), other, parameters);`

This should be allowed as an overload:
`var emitter = ParmeManager.Instance.CreateEmitter("MyEmitterType", other, parameters);`

Per discussion in the FRB channel, you will have to create a resolver dictionary at codegen time to make this performant.

**Comment by KallDrexx** [comment]
Added in 6e39d23166dd4e7fa768af8f80b5ab6aedceb4fe.
