### ISSUE TITLE
Parme Editor should have more predictable camera behavior

### ISSUE THREAD

**Issue by profexorgeek** [KallDrexx/ParME#47]
When working with pixel-art effects, the camera is often zoomed in at 300%. There are several related problems here that I will list in a single issue to centralize discussion instead of creating a ton of issues.

- [x] When zooming, the camera seems to zoom on some position above the emitter. Forcing the user to pan as they zoom to keep the emitter in view. Zoom should zoom in on the center point of where emission is happening.
- [x] When changing any modifier properties, the camera position is reset, moving the emitter off screen. The camera should not be reset when changing parameters (or camera position relative to emitter should be preserved)
- [x] Sometimes this reset is so far that you can't find the emitter again and must restart parme. There should probably be a "reset camera" button next to the movement and angle buttons to easily undo any zooming and panning

![parme-camera-reset](https://user-images.githubusercontent.com/711100/117040691-5e919280-acc7-11eb-8f9b-1f354819c460.gif)

**Comment by KallDrexx** [comment]
Fixed in a65cecaaec477136df8c02c3fae92270e70e2de1, 04fcda067ee7428ef690a1dfa12e1f502b48835a, and d876c6897a43f37567146691b1d72bcf4d5a4e98
