### ISSUE TITLE
Parme should deal with added/removed files

### ISSUE THREAD

**Issue by profexorgeek** [KallDrexx/ParME#49]
Parme should make sure that generated code is synchronized with actual file state/presence:

- [x] When `.emlogic` files are deleted in Glue, the `.Generated.cs` file should be removed
- [x] When glue starts up, `.Generated.cs` files should be regenerated if they are missing

**Comment by KallDrexx** [comment]
First issue fixed in 8b4de99b620e631f02c7a0bb7a333b4c7fb3db89

Second issue cannot be reproduced.  Deleting a generated.cs file and loading glue does seem to regenerate emitter logic code files.
