### ISSUE TITLE
Consider not offering to move png files

### ISSUE THREAD

**Issue by profexorgeek** [KallDrexx/ParME#51]
Parme offers to move files if you select a file that is not local to the .emlogic file location. I think this is a bad user experience with no valid use case. In many cases, Parme may share content with other parts of the content-authoring pipeline. For example, if particles are on a spritesheet or are reused by other parts of the game.

Accidentally clicking the wrong thing can break your entire game and is likely a rare use case. Instead Parme should:

- Assume the content author knows how a file system works and not offer to do things that are better handled as part of a more thoughtful refactor process
- Retain texture area settings so if the content author _does_ break a filepath, they can simply remap the file in Parme and their texture areas will remain intact

**Comment by KallDrexx** [comment]
![Parme do not copy](https://user-images.githubusercontent.com/139393/119239759-25f01680-bb19-11eb-918d-5eb3d70dc2b3.PNG)
