### ISSUE TITLE
Glue plugin does not remove .Generated.cs references when an emlogic file is removed from Glue

### ISSUE THREAD

**Issue by profexorgeek** [KallDrexx/ParME#57]
I realized this when doing a fresh check out of a project - it failed to build because the csproj had references to files that didn't exist on disk because they weren't generated. The parme plugin should have removed these references from the csproj but it did not.

**Repro:**

1. Add an emlogic file to Global Content in Glue
2. Observe that the code file is generated and added to the csproj
3. Remove the emlogic file from Global Content in Glue
4. Observe that the code file continues to exist in the csproj

**Expected behavior:** files removed from glue should be removed from the csproj
**Actual behavior:** files stay in the csproj and fresh checkouts fail to build because the referenced files are not generated

**Gif:**
![parme-fail-to-remove](https://user-images.githubusercontent.com/711100/159193227-49e606b6-9c7d-4428-a38f-eaf107c33232.gif)

**Comment by KallDrexx** [comment]
Fixed in 8b4de99b620e631f02c7a0bb7a333b4c7fb3db89
